export const DEFI_SYMBOLS = [
  'UNIUSDT', 'AAVEUSDT', 'CRVUSDT', 'SNXUSDT', 'COMPUSDT', 'SUSHIUSDT', 'YFIUSDT', 'LDOUSDT'
];

export const MEMECOIN_SYMBOLS = [
  'DOGEUSDT', 'SHIBUSDT', 'PEPEUSDT', 'FLOKIUSDT', 'BONKUSDT', 'BABYDOGEUSDT', 'TURBOUSDT'
];
