name: Prewarm RSI Cache

on:
  schedule:
    - cron: "*/5 * * * *"  # кожні 5 хв
  workflow_dispatch:

jobs:
  hit-prewarm:
    runs-on: ubuntu-latest
    steps:
      - name: Curl prewarm endpoint
        run: |
          curl -fsS --max-time 20 \
            "$VERCEL_BASE_URL/api/prewarm?token=$SECRET" \
            -w "\nHTTP %{http_code}\n"
        env:
          VERCEL_BASE_URL: ${{ secrets.APP_BASE_URL }}
          SECRET: ${{ secrets.SECRET }}
