name: Prewarm RSI Cache
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:
  warm:
    runs-on: ubuntu-latest
    steps:
      - name: Call prewarm endpoint
        run: |
          curl -fsS "$APP_BASE_URL/api/prewarm?token=$SECRET" -w "\nHTTP:%{http_code}\n"
        env:
          APP_BASE_URL: ${{ secrets.APP_BASE_URL }}
          SECRET: ${{ secrets.SECRET }}
